c_obstacle_detector:
  ros__parameters:

    hz: 10                   # ループ周期 [Hz]
    laser_step: 1            # 何本ずつレーザを見るか（全1080本）
    robot_frame: "base_link" # frame_id  基準座標系（どこから見た座標か）

    # --- はずれ値対策 ---
    ignore_dist: 300        # はずれ値(遠方)とみなす距離 [m]
    ignore_pillar: 0.40    # はずれ値(近方)とみなす距離 [m]

    #ごめんyaml機能してないかもしれないTT